pub const RACES: [&str; 116] = [
    "Aetherborn",
    "Aven, Hawk-Headed",
    "Aven, Ibis-Headed",
    "Bugbear",
    "Centaur",
    "Changeling",
    "Dragonborn",
    "Dwarf, Hill",
    "Dwarf, Mountain",
    "Dwarf, Duergar",
    "Dwarf, Mark of Warding",
    "Dwarf, Kaladesh",
    "Elf, High",
    "Elf, Wood",
    "Elf, Drow",
    "Elf, Eladrin",
    "Elf, Sea",
    "Elf, Shadar-kai",
    "Elf, Avariel",
    "Elf, Mark of Shadows",
    "Elf, Grugach",
    "Elf, Bishtahar",
    "Elf, Joraga",
    "Elf, Mul Dara",
    "Elf, Tajuru",
    "Elf, Tirahar",
    "Elf, Vadahar",
    "Firbolg",
    "Genasi, Air",
    "Genasi, Earth",
    "Genasi, Fire",
    "Genasi, Water",
    "Gith, Githyanki",
    "Gith, Githzerai",
    "Gnome, Forest",
    "Gnome, Rock",
    "Gnome, Deep",
    "Gnome, Mark of Scribing",
    "Goblin",
    "Goblin, Grotag",
    "Goblin, Ixalan",
    "Goblin, Lavastep",
    "Goblin, TukTuk",
    "Goliath",
    "Grung",
    "Half-Elf",
    "Half-Elf, Variants",
    "Half-Elf, Mark of Detection",
    "Half-Elf, Mark of Storm",
    "Half-Orc",
    "Half-Orc, Mark of Finding",
    "Halfling, Lightfoot",
    "Halfling, Stout",
    "Halfling, Ghostwise",
    "Halfling, Mark of Healing",
    "Halfling, Mark of Hospitality",
    "Hobgoblin",
    "Human",
    "Human, Variant",
    "Human, Mark of Finding",
    "Human, Mark of Handling",
    "Human, Mark of Making",
    "Human, Mark of Passage",
    "Human, Mark of Sentinel",
    "Human, Gavony",
    "Human, Kessig",
    "Human, Nephalia",
    "Human, Stensia",
    "Kalashtar",
    "Kenku",
    "Khenra",
    "Kobold",
    "Kor",
    "Lizardfolk",
    "Locathah",
    "Loxodon",
    "Merfolk, Blue",
    "Merfolk, Cosi Creed",
    "Merfolk, Emeri Creed",
    "Merfolk, Green",
    "Merfolk, Ula Creed",
    "Minotaur",
    "Naga",
    "Orc",
    "Orc, Eberron",
    "Orc, Ixalan",
    "Other",
    "Shifter, Beasthide",
    "Shifter, Longtooth",
    "Shifter, Swiftstride",
    "Shifter, Wildhunt",
    "Simic Hybrid",
    "Siren",
    "Tabaxi",
    "Tiefling",
    "Tiefling, Abyssal",
    "Tiefling, Baalzebul",
    "Tiefling, Devil's Tongue",
    "Tiefling, Dispater",
    "Tiefling, Feral",
    "Tiefling, Fierna",
    "Tiefling, Glasya",
    "Tiefling, Hellfire",
    "Tiefling, Levistus",
    "Tiefling, Mammon",
    "Tiefling, Mephistopheles",
    "Tiefling, Winged",
    "Tiefling, Zariel",
    "Tortle",
    "Triton",
    "Vampire, Ixalan",
    "Vampire, Zendikar",
    "Vedalken",
    "Verdan",
    "Warforged",
    "Yuan-Ti Pureblood",
];

pub const CLASSES: [&str; 13] = [
    "Artificer",
    "Barbarian",
    "Bard",
    "Cleric",
    "Druid",
    "Fighter",
    "Monk",
    "Paladin",
    "Ranger",
    "Rogue",
    "Sorcerer",
    "Warlock",
    "Wizard",
];